Merge from regression2 (#524)
* Allow to run perfrepo reporter for a specific configuration

* Create the temporary file BEFORE it is used

* Add hazelcast 3.8 plugin

* Add redis32 plugin

* Add infinispan91 plugin

* Bump infinispan version in to 9.1.1-SNAPSHOT

* Add jdg72 plugin

* Specify a released infinispan version for infinispan91 plugin

* Add infinispan92 plugin

* Add infinispan9x plugin

* Add jdg7x plugin

* Extend infinispan92 in infinispan9x

* Upgrade log4j2 to 2.8.2

* Log information about pid (#512)

Sometimes we are facing an issue on Jenkins related with an
"Invalid process identifier".
With this commit, we are now able to know which is the pid number.
Also, I added a single quotation marks to quickly identify an empty
string.

* #516 - Remove distexec-demo

* 514 - Fixed java.lang.NoSuchMethodError: org.jgroups.stack.ProtocolStack.insertProtocol

* Fixed Infinispan Snapshot

Deleted